create table DIM_ACTOR(
 ACTOR_KEY	            NUMBER(22)
,USER_NAME	            VARCHAR2(15)
,FULL_NAME	            VARCHAR2(250)
,FIRST_NAME	            VARCHAR2(150)
,LAST_NAME	            VARCHAR2(150)
,USER_EMAIL	            VARCHAR2(200)
,USER_ACTIVE	        CHAR(1)
,TEAM_NAME	            VARCHAR2(20)
,TEAM_LEAD_USER_NAME	VARCHAR2(15)
,TEAM_LEAD_FULL_NAME	VARCHAR2(250)
,BEGIN_EFFECTIVE_DATE	DATE
,END_EFFECTIVE_DATE	    DATE
)