
  CREATE TABLE "T_STG_CLP_WI_EVNT_HSTRY" 
   (	"BATCHNUM" NUMBER(29,9), 
	"TIME_STAMP" TIMESTAMP (9), 
	"SOURCE_NAME" NVARCHAR2(10), 
	"WORKITEM_ID" NUMBER(38,0), 
	"STATUS" NVARCHAR2(32), 
	"EVENT_DATE" TIMESTAMP (9), 
	"EVENT" NVARCHAR2(32), 
	"TASK" NVARCHAR2(80), 
	"LOC_NAME" NVARCHAR2(32), 
	"ACTOR" NVARCHAR2(32), 
	"REASON_BRIDGE_CODE" NUMBER(29,9)
   );


